### ISSUE TITLE
Bind for 0.0.0.0:9432 failed: port is already allocated

### ISSUE THREAD

**Issue by benstaf** [samyogdhital/listmonk-caddy-reverse-proxy#5]
at the last step, when I run:  `docker compose up -d`

I get the error:

`WARN[0000] /root/listmonk/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 2/3
 ✔ Container listmonk_db       Running                                                                                           0.0s 
 ✔ Container listmonk_app      Running                                                                                           0.0s 
 ⠹ Container listmonk_demo_db  Starting                                                                                          0.2s 
Error response from daemon: driver failed programming external connectivity on endpoint listmonk_demo_db (a0994502c7174f07b82d6318495781ed7b14b660996b43a8010cbc1e41770500): Bind for 0.0.0.0:9432 failed: port is already allocated`

**Comment by samyogdhital** [comment]
@benstaf Did you fix it?

**Comment by benstaf** [comment]
Yes I rebooted the server and it worked.

I re-installed Caddy separately, I didn't use this tutorial
