### ISSUE TITLE
Installation doesn't work 

### ISSUE THREAD

**Issue by benstaf** [samyogdhital/listmonk-caddy-reverse-proxy#6]
Following this tutorial doesn't install Listmonk with caddy, it doesn't even install caddy

**Comment by samyogdhital** [comment]
@benstaf Can you share me what error are you getting?
This repo is meant to be simple if you want to serve listmonk through caddy.

Can you share me your environments?
- OS
- Are you using it on aws?

**Comment by benstaf** [comment]
I installed caddy separately and it worked. This repo didn't work for me
